services:
  smartparkin-go-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: on-failure
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8090:8090"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_TOPIC: ${MQTT_TOPIC}