[ req ]
default_bits       = 4096
default_md         = sha256
distinguished_name = req_distinguished_name
req_extensions     = req_ext
x509_extensions    = req_ext
prompt             = no

[ req_distinguished_name ]
C  = AR
CN = 129.212.182.8

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
IP.1 = 129.212.182.8
