#ifndef CONF_H
#define CONF_H

//CONFIGURACION ID SENSOR TIPO SERIAL FROM BACKOFFICE
const char *SENSOR_ID = "idSerial_CAXDVDFV";
// CONFIGURACION WIFI
const char *WIFI_SSID = "ArangoWifi6";
const char *WIFI_PASSWORD = "SanLORENZO$014v2025";

//CONFIGURACION MQTT BROKER
const char *MQTT_BROKER_HOST = "129.212.182.8";
const int MQTT_BROKER_PORT = 1883;
const char *MQTT_BROKER_TOPIC = "testtopic/sensors";
const char *MQTT_BROKER_USERNAME = "myuser";
const char *MQTT_BROKER_PASSWORD = "mypassword";
//TIEMPO ENTRE MEDICIONES EN MILISEGUNDOS
const int TIME_DELAY = 5000;


#endif // CONF_H
