services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"  # MQTT port
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/passwordfile:/mosquitto/config/passwordfile
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    restart: unless-stopped

volumes:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
